# obj-y += snd-soc-tfa98xx.o
snd-soc-tfa98xx-objs := tfa98xx.o tfa_container.o tfa_dsp.o tfa9890_init.o tfa9888_init.o tfa9891_init.o tfa9897_init.o tfa9887B_init.o tfa9887_init.o

obj-$(CONFIG_SND_SOC_TFA98XX)	+= snd-soc-tfa98xx.o

